// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AccountOAuthProvider(arg1:number):Promise<string>;

export function AccountProxyPasswordStored(arg1:number):Promise<boolean>;

export function AccountSyncStates():Promise<Array<desktop.AccountSyncStateDTO>>;

export function AccountsNeedingPassword():Promise<Array<desktop.AccountDTO>>;

export function ActiveProfile():Promise<desktop.ProfileDTO>;

export function AddAddressBook(arg1:desktop.AddressBookRequest):Promise<desktop.AddressBookDTO>;

export function AddOAuthAccount(arg1:desktop.AddAccountRequest):Promise<desktop.AccountDTO>;

export function AddPasswordAccount(arg1:desktop.AddAccountRequest):Promise<desktop.AccountDTO>;

export function AddVIPSender(arg1:string):Promise<void>;

export function AgentActions():Promise<Array<desktop.AgentActionDTO>>;

export function AgentProposals():Promise<Array<desktop.AgentProposalDTO>>;

export function AllAccounts():Promise<Array<desktop.AccountDTO>>;

export function AllowDomainImages(arg1:number):Promise<void>;

export function AllowRemoteForMessage(arg1:number):Promise<void>;

export function AppVersion():Promise<string>;

export function ApproveAgentProposal(arg1:number):Promise<void>;

export function ArchiveMessage(arg1:number):Promise<desktop.ArchiveUndoDTO>;

export function CancelDownload():Promise<void>;

export function CancelSend(arg1:number):Promise<boolean>;

export function CheckAccountPassword(arg1:number,arg2:string):Promise<desktop.PasswordCheckDTO>;

export function CheckForUpdates():Promise<desktop.UpdateCheckResult>;

export function CheckSMIMERevocation(arg1:number):Promise<desktop.SMIMERevocationDTO>;

export function ChooseArchiveExportFolder():Promise<string>;

export function ChooseCAFile():Promise<desktop.CAFileDTO>;

export function ChooseMailFiles():Promise<Array<string>>;

export function ChooseThunderbirdProfile():Promise<Array<desktop.ThunderbirdProfileDTO>>;

export function ClearAgentActions():Promise<void>;

export function ClearDevActivity():Promise<void>;

export function ClearSentOutbox():Promise<void>;

export function CloseWindow():Promise<void>;

export function ComposeProtectionStatus(arg1:number,arg2:Array<string>):Promise<desktop.ProtectionStatusDTO>;

export function ConfirmThemeImport(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<desktop.ThemeInfoDTO>;

export function ConsumePendingMailto():Promise<desktop.PendingMailtoDTO>;

export function CreateFolder(arg1:desktop.CreateFolderRequest):Promise<desktop.FolderDTO>;

export function CreateProfile(arg1:desktop.ProfileRequest):Promise<desktop.ProfileDTO>;

export function DefaultMailClientStatus():Promise<desktop.DefaultMailStatusDTO>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteAddress(arg1:string):Promise<void>;

export function DeleteContact(arg1:number,arg2:boolean):Promise<desktop.ContactConflictDTO>;

export function DeleteDraft(arg1:number):Promise<void>;

export function DeleteFolder(arg1:number):Promise<void>;

export function DeleteLogs():Promise<void>;

export function DeleteMessage(arg1:number):Promise<void>;

export function DeletePGPKey(arg1:string):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function DeleteSignature(arg1:number):Promise<void>;

export function DeleteTheme(arg1:string):Promise<void>;

export function DeleteView(arg1:number):Promise<void>;

export function DevActivity(arg1:number):Promise<desktop.DevActivityDTO>;

export function DevProcessStats():Promise<desktop.DevProcessDTO>;

export function DevToolsEnabled():Promise<boolean>;

export function DiscardAgentProposal(arg1:number):Promise<void>;

export function DiscardFailedSend(arg1:number):Promise<boolean>;

export function DiscoverAddressBooks(arg1:desktop.AddressBookRequest):Promise<Array<desktop.DiscoveredBookDTO>>;

export function DiscoverConfig(arg1:string):Promise<desktop.DiscoveredDTO>;

export function DismissCrashReport():Promise<void>;

export function DismissPasswordPrompt(arg1:number):Promise<void>;

export function DownloadMessageOffline(arg1:number):Promise<void>;

export function DownloadRange(arg1:string,arg2:boolean):Promise<void>;

export function EmptyTrash(arg1:number):Promise<number>;

export function ExportData(arg1:Array<string>,arg2:string):Promise<string>;

export function ExportMessagePrintView(arg1:number):Promise<void>;

export function ExportPGPKey(arg1:string,arg2:boolean):Promise<string>;

export function ExportTheme(arg1:string):Promise<string>;

export function FetchOlderMessages(arg1:desktop.ListMessagesRequest):Promise<desktop.FetchOlderResult>;

export function FindThunderbirdProfiles():Promise<Array<desktop.ThunderbirdProfileDTO>>;

export function ForgetPGPPassphrase(arg1:string):Promise<void>;

export function GetAccountPGPKey(arg1:number):Promise<string>;

export function GetAccountSignatures(arg1:number):Promise<desktop.AccountSignaturesDTO>;

export function GetDiagnostics():Promise<string>;

export function GetLogStatus():Promise<desktop.LogStatusDTO>;

export function GetMCPConfig():Promise<desktop.MCPConfigDTO>;

export function GetMessage(arg1:number):Promise<desktop.MessageDetailDTO>;

export function GetMessageHTML(arg1:number,arg2:boolean,arg3:boolean):Promise<string>;

export function GetMessageSource(arg1:number):Promise<string>;

export function GetProxyConfig():Promise<desktop.ProxyConfigDTO>;

export function GetSetting(arg1:string):Promise<desktop.SettingResult>;

export function GetThemeApply(arg1:string):Promise<desktop.ThemeApplyDTO>;

export function GetThemeDraft(arg1:string):Promise<desktop.ThemeDraftDTO>;

export function GetUIPrefs():Promise<desktop.UIPrefsDTO>;

export function GetUserLocale(arg1:string):Promise<desktop.UserLocaleApplyDTO>;

export function GetVirusTotalConfig():Promise<desktop.VirusTotalConfigDTO>;

export function ImportData(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function ImportMailFiles(arg1:Array<string>):Promise<void>;

export function ImportPGPKey():Promise<Array<desktop.PGPKeyDTO>>;

export function ImportThunderbirdAccounts(arg1:string,arg2:Array<string>):Promise<number>;

export function ImportThunderbirdFolders(arg1:Array<string>):Promise<void>;

export function InspectBackupFile():Promise<desktop.BackupInfoDTO>;

export function IsDemoMode():Promise<boolean>;

export function IsDevMode():Promise<boolean>;

export function IsNightly():Promise<boolean>;

export function Licenses():Promise<string>;

export function ListAccounts():Promise<Array<desktop.AccountDTO>>;

export function ListAddressBooks():Promise<Array<desktop.AddressBookDTO>>;

export function ListAddresses():Promise<Array<desktop.AddressBookEntryDTO>>;

export function ListContacts(arg1:number):Promise<Array<desktop.ContactDTO>>;

export function ListDrafts():Promise<Array<desktop.DraftDTO>>;

export function ListFolders(arg1:number):Promise<Array<desktop.FolderDTO>>;

export function ListImageAllowlist():Promise<Array<desktop.ImageAllowEntryDTO>>;

export function ListMessages(arg1:desktop.ListMessagesRequest):Promise<desktop.MessageListDTO>;

export function ListOAuthProviders():Promise<Record<string, string>>;

export function ListOutbox():Promise<Array<desktop.OutboxRowDTO>>;

export function ListPGPKeys():Promise<Array<desktop.PGPKeyDTO>>;

export function ListPinnedFolders():Promise<Array<desktop.FolderDTO>>;

export function ListProfiles():Promise<Array<desktop.ProfileDTO>>;

export function ListSignatures():Promise<Array<desktop.SignatureDTO>>;

export function ListSystemFonts():Promise<Array<string>>;

export function ListThemes():Promise<Array<desktop.ThemeInfoDTO>>;

export function ListUnifiedViews():Promise<Array<desktop.UnifiedViewDTO>>;

export function ListUserLocales():Promise<Array<desktop.UserLocaleDTO>>;

export function ListVIPSenders():Promise<Array<string>>;

export function ListViews():Promise<Array<desktop.ViewDTO>>;

export function MCPPermissions():Promise<Array<desktop.MCPPermissionDTO>>;

export function MarkSenderVIP(arg1:number):Promise<void>;

export function MessageIDs(arg1:desktop.ListMessagesRequest):Promise<desktop.MessageIDsDTO>;

export function MoveMessage(arg1:number,arg2:number):Promise<desktop.ArchiveUndoDTO>;

export function OpenCrashReport():Promise<void>;

export function OpenLocalesFolder():Promise<void>;

export function OpenLogFolder():Promise<void>;

export function OpenThemesFolder():Promise<void>;

export function PreviewArchiveExportName(arg1:string,arg2:string):Promise<string>;

export function PreviewThemeImport():Promise<desktop.ThemeImportPreviewDTO>;

export function ProbeAccountCertificates(arg1:number):Promise<Array<desktop.UntrustedCertDTO>>;

export function ProgramLicense():Promise<string>;

export function ReadAttachment(arg1:number,arg2:number):Promise<desktop.AttachmentContentDTO>;

export function ReauthorizeOAuthAccount(arg1:number):Promise<void>;

export function RebuildMenu():Promise<void>;

export function RegenerateMCPToken():Promise<string>;

export function RemoveAccountTrustedCertificate(arg1:number,arg2:string):Promise<void>;

export function RemoveAddressBook(arg1:number):Promise<void>;

export function RemoveImageAllow(arg1:string,arg2:string):Promise<void>;

export function RemoveOffline(arg1:number):Promise<void>;

export function RemoveVIPSender(arg1:string):Promise<void>;

export function RenameFolder(arg1:number,arg2:string):Promise<void>;

export function ReorderAccounts(arg1:Array<number>):Promise<void>;

export function ReorderFolders(arg1:Array<number>):Promise<void>;

export function ReorderPinnedFolders(arg1:Array<number>):Promise<void>;

export function ReorderUnifiedViews(arg1:Array<string>):Promise<void>;

export function ReorderViews(arg1:Array<number>):Promise<void>;

export function ResumePendingDownload():Promise<void>;

export function RetrySend(arg1:number):Promise<boolean>;

export function SMIMERevocationEnabled():Promise<boolean>;

export function SaveAllAttachments(arg1:number):Promise<string>;

export function SaveAttachment(arg1:number,arg2:number):Promise<string>;

export function SaveContact(arg1:desktop.ContactRequest):Promise<desktop.ContactConflictDTO>;

export function SaveCustomTheme(arg1:desktop.SaveThemeRequest):Promise<desktop.ThemeInfoDTO>;

export function SaveDraft(arg1:number,arg2:desktop.ComposeRequest):Promise<number>;

export function SaveLocaleTemplate(arg1:string):Promise<string>;

export function SaveSignature(arg1:desktop.SignatureDTO):Promise<desktop.SignatureDTO>;

export function SaveView(arg1:desktop.ViewDTO):Promise<desktop.ViewDTO>;

export function ScanAttachment(arg1:number,arg2:number):Promise<desktop.VerdictDTO>;

export function ScanMessage(arg1:number,arg2:boolean,arg3:boolean):Promise<desktop.MessageScanDTO>;

export function ScanURL(arg1:string):Promise<desktop.VerdictDTO>;

export function Search(arg1:desktop.SearchRequestDTO):Promise<desktop.SearchResultDTO>;

export function SearchAddresses(arg1:string,arg2:number):Promise<Array<desktop.AddressBookEntryDTO>>;

export function SearchMessageIDs(arg1:desktop.SearchRequestDTO):Promise<desktop.MessageIDsDTO>;

export function SendMessage(arg1:desktop.ComposeRequest):Promise<number>;

export function SenderPhotos(arg1:string):Promise<Array<string>>;

export function SetAccountCA(arg1:number,arg2:string):Promise<void>;

export function SetAccountPGPKey(arg1:number,arg2:string):Promise<void>;

export function SetAccountPassword(arg1:number,arg2:string):Promise<void>;

export function SetAccountSignatures(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SetDefaultMailClient():Promise<void>;

export function SetFlagColor(arg1:number,arg2:number):Promise<void>;

export function SetFlagged(arg1:number,arg2:boolean):Promise<void>;

export function SetFolderPinned(arg1:number,arg2:boolean):Promise<void>;

export function SetFolderRole(arg1:number,arg2:string):Promise<void>;

export function SetFolderSyncExcluded(arg1:number,arg2:boolean):Promise<void>;

export function SetMCPEnabled(arg1:boolean):Promise<void>;

export function SetMCPPermission(arg1:string,arg2:boolean):Promise<void>;

export function SetMCPPort(arg1:number):Promise<void>;

export function SetMailActionsEnabled(arg1:boolean):Promise<void>;

export function SetProxyConfig(arg1:desktop.ProxyConfigDTO):Promise<void>;

export function SetSMIMERevocation(arg1:boolean):Promise<void>;

export function SetSeen(arg1:number,arg2:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetUnreadBadge(arg1:number):Promise<void>;

export function SetVirusTotalAPIKey(arg1:string):Promise<void>;

export function SetVirusTotalAutoScanAttachments(arg1:boolean):Promise<void>;

export function SetVirusTotalAutoScanLinks(arg1:boolean):Promise<void>;

export function SetVirusTotalEnabled(arg1:boolean):Promise<void>;

export function SetWindowTheme(arg1:boolean):Promise<void>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function SignerFingerprint(arg1:number):Promise<string>;

export function SnoozeMessage(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function StartAccountSync(arg1:number):Promise<void>;

export function SwitchProfile(arg1:number):Promise<void>;

export function SyncAccountNow(arg1:number):Promise<void>;

export function SyncContacts():Promise<void>;

export function SystemColorScheme():Promise<string>;

export function TestAccountRoute(arg1:desktop.RouteTestRequest):Promise<void>;

export function TestConnection(arg1:desktop.TestConnectionRequest):Promise<desktop.ConnectionTestDTO>;

export function TestProxy(arg1:desktop.ProxyConfigDTO):Promise<void>;

export function TitleBarDoubleClick():Promise<void>;

export function TriggerSync():Promise<void>;

export function TrustAccountCertificate(arg1:number,arg2:string):Promise<void>;

export function TrustSenderImages(arg1:number):Promise<void>;

export function UnarchiveMessage(arg1:string,arg2:number,arg3:number):Promise<void>;

export function UndoDelete(arg1:number):Promise<void>;

export function UnlockMessage(arg1:number,arg2:string):Promise<void>;

export function UnlockPGPKey(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UnmarkSenderVIP(arg1:number):Promise<void>;

export function UnsealDraft(arg1:number,arg2:string):Promise<desktop.DraftDTO>;

export function UnsnoozeMessage(arg1:number):Promise<void>;

export function Unsubscribe(arg1:number):Promise<void>;

export function UpdateAccount(arg1:desktop.UpdateAccountRequest):Promise<desktop.AccountDTO>;

export function UpdateAddressBook(arg1:desktop.AddressBookRequest):Promise<desktop.AddressBookDTO>;

export function UpdateProfile(arg1:desktop.ProfileRequest):Promise<desktop.ProfileDTO>;
