// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccountOAuthProvider(arg1) {
  return window['go']['desktop']['App']['AccountOAuthProvider'](arg1);
}

export function AccountProxyPasswordStored(arg1) {
  return window['go']['desktop']['App']['AccountProxyPasswordStored'](arg1);
}

export function AccountSyncStates() {
  return window['go']['desktop']['App']['AccountSyncStates']();
}

export function AccountsNeedingPassword() {
  return window['go']['desktop']['App']['AccountsNeedingPassword']();
}

export function ActiveProfile() {
  return window['go']['desktop']['App']['ActiveProfile']();
}

export function AddAddressBook(arg1) {
  return window['go']['desktop']['App']['AddAddressBook'](arg1);
}

export function AddOAuthAccount(arg1) {
  return window['go']['desktop']['App']['AddOAuthAccount'](arg1);
}

export function AddPasswordAccount(arg1) {
  return window['go']['desktop']['App']['AddPasswordAccount'](arg1);
}

export function AddVIPSender(arg1) {
  return window['go']['desktop']['App']['AddVIPSender'](arg1);
}

export function AgentActions() {
  return window['go']['desktop']['App']['AgentActions']();
}

export function AgentProposals() {
  return window['go']['desktop']['App']['AgentProposals']();
}

export function AllAccounts() {
  return window['go']['desktop']['App']['AllAccounts']();
}

export function AllowDomainImages(arg1) {
  return window['go']['desktop']['App']['AllowDomainImages'](arg1);
}

export function AllowRemoteForMessage(arg1) {
  return window['go']['desktop']['App']['AllowRemoteForMessage'](arg1);
}

export function AppVersion() {
  return window['go']['desktop']['App']['AppVersion']();
}

export function ApproveAgentProposal(arg1) {
  return window['go']['desktop']['App']['ApproveAgentProposal'](arg1);
}

export function ArchiveMessage(arg1) {
  return window['go']['desktop']['App']['ArchiveMessage'](arg1);
}

export function CancelDownload() {
  return window['go']['desktop']['App']['CancelDownload']();
}

export function CancelSend(arg1) {
  return window['go']['desktop']['App']['CancelSend'](arg1);
}

export function CheckAccountPassword(arg1, arg2) {
  return window['go']['desktop']['App']['CheckAccountPassword'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['desktop']['App']['CheckForUpdates']();
}

export function CheckSMIMERevocation(arg1) {
  return window['go']['desktop']['App']['CheckSMIMERevocation'](arg1);
}

export function ChooseArchiveExportFolder() {
  return window['go']['desktop']['App']['ChooseArchiveExportFolder']();
}

export function ChooseCAFile() {
  return window['go']['desktop']['App']['ChooseCAFile']();
}

export function ChooseMailFiles() {
  return window['go']['desktop']['App']['ChooseMailFiles']();
}

export function ChooseThunderbirdProfile() {
  return window['go']['desktop']['App']['ChooseThunderbirdProfile']();
}

export function ClearAgentActions() {
  return window['go']['desktop']['App']['ClearAgentActions']();
}

export function ClearDevActivity() {
  return window['go']['desktop']['App']['ClearDevActivity']();
}

export function ClearSentOutbox() {
  return window['go']['desktop']['App']['ClearSentOutbox']();
}

export function CloseWindow() {
  return window['go']['desktop']['App']['CloseWindow']();
}

export function ComposeProtectionStatus(arg1, arg2) {
  return window['go']['desktop']['App']['ComposeProtectionStatus'](arg1, arg2);
}

export function ConfirmThemeImport(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['ConfirmThemeImport'](arg1, arg2, arg3, arg4);
}

export function ConsumePendingMailto() {
  return window['go']['desktop']['App']['ConsumePendingMailto']();
}

export function CreateFolder(arg1) {
  return window['go']['desktop']['App']['CreateFolder'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['desktop']['App']['CreateProfile'](arg1);
}

export function DefaultMailClientStatus() {
  return window['go']['desktop']['App']['DefaultMailClientStatus']();
}

export function DeleteAccount(arg1) {
  return window['go']['desktop']['App']['DeleteAccount'](arg1);
}

export function DeleteAddress(arg1) {
  return window['go']['desktop']['App']['DeleteAddress'](arg1);
}

export function DeleteContact(arg1, arg2) {
  return window['go']['desktop']['App']['DeleteContact'](arg1, arg2);
}

export function DeleteDraft(arg1) {
  return window['go']['desktop']['App']['DeleteDraft'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['desktop']['App']['DeleteFolder'](arg1);
}

export function DeleteLogs() {
  return window['go']['desktop']['App']['DeleteLogs']();
}

export function DeleteMessage(arg1) {
  return window['go']['desktop']['App']['DeleteMessage'](arg1);
}

export function DeletePGPKey(arg1) {
  return window['go']['desktop']['App']['DeletePGPKey'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['desktop']['App']['DeleteProfile'](arg1);
}

export function DeleteSignature(arg1) {
  return window['go']['desktop']['App']['DeleteSignature'](arg1);
}

export function DeleteTheme(arg1) {
  return window['go']['desktop']['App']['DeleteTheme'](arg1);
}

export function DeleteView(arg1) {
  return window['go']['desktop']['App']['DeleteView'](arg1);
}

export function DevActivity(arg1) {
  return window['go']['desktop']['App']['DevActivity'](arg1);
}

export function DevProcessStats() {
  return window['go']['desktop']['App']['DevProcessStats']();
}

export function DevToolsEnabled() {
  return window['go']['desktop']['App']['DevToolsEnabled']();
}

export function DiscardAgentProposal(arg1) {
  return window['go']['desktop']['App']['DiscardAgentProposal'](arg1);
}

export function DiscardFailedSend(arg1) {
  return window['go']['desktop']['App']['DiscardFailedSend'](arg1);
}

export function DiscoverAddressBooks(arg1) {
  return window['go']['desktop']['App']['DiscoverAddressBooks'](arg1);
}

export function DiscoverConfig(arg1) {
  return window['go']['desktop']['App']['DiscoverConfig'](arg1);
}

export function DismissCrashReport() {
  return window['go']['desktop']['App']['DismissCrashReport']();
}

export function DismissPasswordPrompt(arg1) {
  return window['go']['desktop']['App']['DismissPasswordPrompt'](arg1);
}

export function DownloadMessageOffline(arg1) {
  return window['go']['desktop']['App']['DownloadMessageOffline'](arg1);
}

export function DownloadRange(arg1, arg2) {
  return window['go']['desktop']['App']['DownloadRange'](arg1, arg2);
}

export function EmptyTrash(arg1) {
  return window['go']['desktop']['App']['EmptyTrash'](arg1);
}

export function ExportData(arg1, arg2) {
  return window['go']['desktop']['App']['ExportData'](arg1, arg2);
}

export function ExportMessagePrintView(arg1) {
  return window['go']['desktop']['App']['ExportMessagePrintView'](arg1);
}

export function ExportPGPKey(arg1, arg2) {
  return window['go']['desktop']['App']['ExportPGPKey'](arg1, arg2);
}

export function ExportTheme(arg1) {
  return window['go']['desktop']['App']['ExportTheme'](arg1);
}

export function FetchOlderMessages(arg1) {
  return window['go']['desktop']['App']['FetchOlderMessages'](arg1);
}

export function FindThunderbirdProfiles() {
  return window['go']['desktop']['App']['FindThunderbirdProfiles']();
}

export function ForgetPGPPassphrase(arg1) {
  return window['go']['desktop']['App']['ForgetPGPPassphrase'](arg1);
}

export function GetAccountPGPKey(arg1) {
  return window['go']['desktop']['App']['GetAccountPGPKey'](arg1);
}

export function GetAccountSignatures(arg1) {
  return window['go']['desktop']['App']['GetAccountSignatures'](arg1);
}

export function GetDiagnostics() {
  return window['go']['desktop']['App']['GetDiagnostics']();
}

export function GetLogStatus() {
  return window['go']['desktop']['App']['GetLogStatus']();
}

export function GetMCPConfig() {
  return window['go']['desktop']['App']['GetMCPConfig']();
}

export function GetMessage(arg1) {
  return window['go']['desktop']['App']['GetMessage'](arg1);
}

export function GetMessageHTML(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['GetMessageHTML'](arg1, arg2, arg3);
}

export function GetMessageSource(arg1) {
  return window['go']['desktop']['App']['GetMessageSource'](arg1);
}

export function GetProxyConfig() {
  return window['go']['desktop']['App']['GetProxyConfig']();
}

export function GetSetting(arg1) {
  return window['go']['desktop']['App']['GetSetting'](arg1);
}

export function GetThemeApply(arg1) {
  return window['go']['desktop']['App']['GetThemeApply'](arg1);
}

export function GetThemeDraft(arg1) {
  return window['go']['desktop']['App']['GetThemeDraft'](arg1);
}

export function GetUIPrefs() {
  return window['go']['desktop']['App']['GetUIPrefs']();
}

export function GetUserLocale(arg1) {
  return window['go']['desktop']['App']['GetUserLocale'](arg1);
}

export function GetVirusTotalConfig() {
  return window['go']['desktop']['App']['GetVirusTotalConfig']();
}

export function ImportData(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ImportData'](arg1, arg2, arg3);
}

export function ImportMailFiles(arg1) {
  return window['go']['desktop']['App']['ImportMailFiles'](arg1);
}

export function ImportPGPKey() {
  return window['go']['desktop']['App']['ImportPGPKey']();
}

export function ImportThunderbirdAccounts(arg1, arg2) {
  return window['go']['desktop']['App']['ImportThunderbirdAccounts'](arg1, arg2);
}

export function ImportThunderbirdFolders(arg1) {
  return window['go']['desktop']['App']['ImportThunderbirdFolders'](arg1);
}

export function InspectBackupFile() {
  return window['go']['desktop']['App']['InspectBackupFile']();
}

export function IsDemoMode() {
  return window['go']['desktop']['App']['IsDemoMode']();
}

export function IsDevMode() {
  return window['go']['desktop']['App']['IsDevMode']();
}

export function IsNightly() {
  return window['go']['desktop']['App']['IsNightly']();
}

export function Licenses() {
  return window['go']['desktop']['App']['Licenses']();
}

export function ListAccounts() {
  return window['go']['desktop']['App']['ListAccounts']();
}

export function ListAddressBooks() {
  return window['go']['desktop']['App']['ListAddressBooks']();
}

export function ListAddresses() {
  return window['go']['desktop']['App']['ListAddresses']();
}

export function ListContacts(arg1) {
  return window['go']['desktop']['App']['ListContacts'](arg1);
}

export function ListDrafts() {
  return window['go']['desktop']['App']['ListDrafts']();
}

export function ListFolders(arg1) {
  return window['go']['desktop']['App']['ListFolders'](arg1);
}

export function ListImageAllowlist() {
  return window['go']['desktop']['App']['ListImageAllowlist']();
}

export function ListMessages(arg1) {
  return window['go']['desktop']['App']['ListMessages'](arg1);
}

export function ListOAuthProviders() {
  return window['go']['desktop']['App']['ListOAuthProviders']();
}

export function ListOutbox() {
  return window['go']['desktop']['App']['ListOutbox']();
}

export function ListPGPKeys() {
  return window['go']['desktop']['App']['ListPGPKeys']();
}

export function ListPinnedFolders() {
  return window['go']['desktop']['App']['ListPinnedFolders']();
}

export function ListProfiles() {
  return window['go']['desktop']['App']['ListProfiles']();
}

export function ListSignatures() {
  return window['go']['desktop']['App']['ListSignatures']();
}

export function ListSystemFonts() {
  return window['go']['desktop']['App']['ListSystemFonts']();
}

export function ListThemes() {
  return window['go']['desktop']['App']['ListThemes']();
}

export function ListUnifiedViews() {
  return window['go']['desktop']['App']['ListUnifiedViews']();
}

export function ListUserLocales() {
  return window['go']['desktop']['App']['ListUserLocales']();
}

export function ListVIPSenders() {
  return window['go']['desktop']['App']['ListVIPSenders']();
}

export function ListViews() {
  return window['go']['desktop']['App']['ListViews']();
}

export function MCPPermissions() {
  return window['go']['desktop']['App']['MCPPermissions']();
}

export function MarkSenderVIP(arg1) {
  return window['go']['desktop']['App']['MarkSenderVIP'](arg1);
}

export function MessageIDs(arg1) {
  return window['go']['desktop']['App']['MessageIDs'](arg1);
}

export function MoveMessage(arg1, arg2) {
  return window['go']['desktop']['App']['MoveMessage'](arg1, arg2);
}

export function OpenCrashReport() {
  return window['go']['desktop']['App']['OpenCrashReport']();
}

export function OpenLocalesFolder() {
  return window['go']['desktop']['App']['OpenLocalesFolder']();
}

export function OpenLogFolder() {
  return window['go']['desktop']['App']['OpenLogFolder']();
}

export function OpenThemesFolder() {
  return window['go']['desktop']['App']['OpenThemesFolder']();
}

export function PreviewArchiveExportName(arg1, arg2) {
  return window['go']['desktop']['App']['PreviewArchiveExportName'](arg1, arg2);
}

export function PreviewThemeImport() {
  return window['go']['desktop']['App']['PreviewThemeImport']();
}

export function ProbeAccountCertificates(arg1) {
  return window['go']['desktop']['App']['ProbeAccountCertificates'](arg1);
}

export function ProgramLicense() {
  return window['go']['desktop']['App']['ProgramLicense']();
}

export function ReadAttachment(arg1, arg2) {
  return window['go']['desktop']['App']['ReadAttachment'](arg1, arg2);
}

export function ReauthorizeOAuthAccount(arg1) {
  return window['go']['desktop']['App']['ReauthorizeOAuthAccount'](arg1);
}

export function RebuildMenu() {
  return window['go']['desktop']['App']['RebuildMenu']();
}

export function RegenerateMCPToken() {
  return window['go']['desktop']['App']['RegenerateMCPToken']();
}

export function RemoveAccountTrustedCertificate(arg1, arg2) {
  return window['go']['desktop']['App']['RemoveAccountTrustedCertificate'](arg1, arg2);
}

export function RemoveAddressBook(arg1) {
  return window['go']['desktop']['App']['RemoveAddressBook'](arg1);
}

export function RemoveImageAllow(arg1, arg2) {
  return window['go']['desktop']['App']['RemoveImageAllow'](arg1, arg2);
}

export function RemoveOffline(arg1) {
  return window['go']['desktop']['App']['RemoveOffline'](arg1);
}

export function RemoveVIPSender(arg1) {
  return window['go']['desktop']['App']['RemoveVIPSender'](arg1);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['desktop']['App']['RenameFolder'](arg1, arg2);
}

export function ReorderAccounts(arg1) {
  return window['go']['desktop']['App']['ReorderAccounts'](arg1);
}

export function ReorderFolders(arg1) {
  return window['go']['desktop']['App']['ReorderFolders'](arg1);
}

export function ReorderPinnedFolders(arg1) {
  return window['go']['desktop']['App']['ReorderPinnedFolders'](arg1);
}

export function ReorderUnifiedViews(arg1) {
  return window['go']['desktop']['App']['ReorderUnifiedViews'](arg1);
}

export function ReorderViews(arg1) {
  return window['go']['desktop']['App']['ReorderViews'](arg1);
}

export function ResumePendingDownload() {
  return window['go']['desktop']['App']['ResumePendingDownload']();
}

export function RetrySend(arg1) {
  return window['go']['desktop']['App']['RetrySend'](arg1);
}

export function SMIMERevocationEnabled() {
  return window['go']['desktop']['App']['SMIMERevocationEnabled']();
}

export function SaveAllAttachments(arg1) {
  return window['go']['desktop']['App']['SaveAllAttachments'](arg1);
}

export function SaveAttachment(arg1, arg2) {
  return window['go']['desktop']['App']['SaveAttachment'](arg1, arg2);
}

export function SaveContact(arg1) {
  return window['go']['desktop']['App']['SaveContact'](arg1);
}

export function SaveCustomTheme(arg1) {
  return window['go']['desktop']['App']['SaveCustomTheme'](arg1);
}

export function SaveDraft(arg1, arg2) {
  return window['go']['desktop']['App']['SaveDraft'](arg1, arg2);
}

export function SaveLocaleTemplate(arg1) {
  return window['go']['desktop']['App']['SaveLocaleTemplate'](arg1);
}

export function SaveSignature(arg1) {
  return window['go']['desktop']['App']['SaveSignature'](arg1);
}

export function SaveView(arg1) {
  return window['go']['desktop']['App']['SaveView'](arg1);
}

export function ScanAttachment(arg1, arg2) {
  return window['go']['desktop']['App']['ScanAttachment'](arg1, arg2);
}

export function ScanMessage(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ScanMessage'](arg1, arg2, arg3);
}

export function ScanURL(arg1) {
  return window['go']['desktop']['App']['ScanURL'](arg1);
}

export function Search(arg1) {
  return window['go']['desktop']['App']['Search'](arg1);
}

export function SearchAddresses(arg1, arg2) {
  return window['go']['desktop']['App']['SearchAddresses'](arg1, arg2);
}

export function SearchMessageIDs(arg1) {
  return window['go']['desktop']['App']['SearchMessageIDs'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['desktop']['App']['SendMessage'](arg1);
}

export function SenderPhotos(arg1) {
  return window['go']['desktop']['App']['SenderPhotos'](arg1);
}

export function SetAccountCA(arg1, arg2) {
  return window['go']['desktop']['App']['SetAccountCA'](arg1, arg2);
}

export function SetAccountPGPKey(arg1, arg2) {
  return window['go']['desktop']['App']['SetAccountPGPKey'](arg1, arg2);
}

export function SetAccountPassword(arg1, arg2) {
  return window['go']['desktop']['App']['SetAccountPassword'](arg1, arg2);
}

export function SetAccountSignatures(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SetAccountSignatures'](arg1, arg2, arg3);
}

export function SetDefaultMailClient() {
  return window['go']['desktop']['App']['SetDefaultMailClient']();
}

export function SetFlagColor(arg1, arg2) {
  return window['go']['desktop']['App']['SetFlagColor'](arg1, arg2);
}

export function SetFlagged(arg1, arg2) {
  return window['go']['desktop']['App']['SetFlagged'](arg1, arg2);
}

export function SetFolderPinned(arg1, arg2) {
  return window['go']['desktop']['App']['SetFolderPinned'](arg1, arg2);
}

export function SetFolderRole(arg1, arg2) {
  return window['go']['desktop']['App']['SetFolderRole'](arg1, arg2);
}

export function SetFolderSyncExcluded(arg1, arg2) {
  return window['go']['desktop']['App']['SetFolderSyncExcluded'](arg1, arg2);
}

export function SetMCPEnabled(arg1) {
  return window['go']['desktop']['App']['SetMCPEnabled'](arg1);
}

export function SetMCPPermission(arg1, arg2) {
  return window['go']['desktop']['App']['SetMCPPermission'](arg1, arg2);
}

export function SetMCPPort(arg1) {
  return window['go']['desktop']['App']['SetMCPPort'](arg1);
}

export function SetMailActionsEnabled(arg1) {
  return window['go']['desktop']['App']['SetMailActionsEnabled'](arg1);
}

export function SetProxyConfig(arg1) {
  return window['go']['desktop']['App']['SetProxyConfig'](arg1);
}

export function SetSMIMERevocation(arg1) {
  return window['go']['desktop']['App']['SetSMIMERevocation'](arg1);
}

export function SetSeen(arg1, arg2) {
  return window['go']['desktop']['App']['SetSeen'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['desktop']['App']['SetSetting'](arg1, arg2);
}

export function SetUnreadBadge(arg1) {
  return window['go']['desktop']['App']['SetUnreadBadge'](arg1);
}

export function SetVirusTotalAPIKey(arg1) {
  return window['go']['desktop']['App']['SetVirusTotalAPIKey'](arg1);
}

export function SetVirusTotalAutoScanAttachments(arg1) {
  return window['go']['desktop']['App']['SetVirusTotalAutoScanAttachments'](arg1);
}

export function SetVirusTotalAutoScanLinks(arg1) {
  return window['go']['desktop']['App']['SetVirusTotalAutoScanLinks'](arg1);
}

export function SetVirusTotalEnabled(arg1) {
  return window['go']['desktop']['App']['SetVirusTotalEnabled'](arg1);
}

export function SetWindowTheme(arg1) {
  return window['go']['desktop']['App']['SetWindowTheme'](arg1);
}

export function SetWindowTitle(arg1) {
  return window['go']['desktop']['App']['SetWindowTitle'](arg1);
}

export function SignerFingerprint(arg1) {
  return window['go']['desktop']['App']['SignerFingerprint'](arg1);
}

export function SnoozeMessage(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SnoozeMessage'](arg1, arg2, arg3);
}

export function StartAccountSync(arg1) {
  return window['go']['desktop']['App']['StartAccountSync'](arg1);
}

export function SwitchProfile(arg1) {
  return window['go']['desktop']['App']['SwitchProfile'](arg1);
}

export function SyncAccountNow(arg1) {
  return window['go']['desktop']['App']['SyncAccountNow'](arg1);
}

export function SyncContacts() {
  return window['go']['desktop']['App']['SyncContacts']();
}

export function SystemColorScheme() {
  return window['go']['desktop']['App']['SystemColorScheme']();
}

export function TestAccountRoute(arg1) {
  return window['go']['desktop']['App']['TestAccountRoute'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['desktop']['App']['TestConnection'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['desktop']['App']['TestProxy'](arg1);
}

export function TitleBarDoubleClick() {
  return window['go']['desktop']['App']['TitleBarDoubleClick']();
}

export function TriggerSync() {
  return window['go']['desktop']['App']['TriggerSync']();
}

export function TrustAccountCertificate(arg1, arg2) {
  return window['go']['desktop']['App']['TrustAccountCertificate'](arg1, arg2);
}

export function TrustSenderImages(arg1) {
  return window['go']['desktop']['App']['TrustSenderImages'](arg1);
}

export function UnarchiveMessage(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['UnarchiveMessage'](arg1, arg2, arg3);
}

export function UndoDelete(arg1) {
  return window['go']['desktop']['App']['UndoDelete'](arg1);
}

export function UnlockMessage(arg1, arg2) {
  return window['go']['desktop']['App']['UnlockMessage'](arg1, arg2);
}

export function UnlockPGPKey(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['UnlockPGPKey'](arg1, arg2, arg3);
}

export function UnmarkSenderVIP(arg1) {
  return window['go']['desktop']['App']['UnmarkSenderVIP'](arg1);
}

export function UnsealDraft(arg1, arg2) {
  return window['go']['desktop']['App']['UnsealDraft'](arg1, arg2);
}

export function UnsnoozeMessage(arg1) {
  return window['go']['desktop']['App']['UnsnoozeMessage'](arg1);
}

export function Unsubscribe(arg1) {
  return window['go']['desktop']['App']['Unsubscribe'](arg1);
}

export function UpdateAccount(arg1) {
  return window['go']['desktop']['App']['UpdateAccount'](arg1);
}

export function UpdateAddressBook(arg1) {
  return window['go']['desktop']['App']['UpdateAddressBook'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['desktop']['App']['UpdateProfile'](arg1);
}
